#pragma once
#include "pe.hpp"
#include <bcrypt.h>
#include <filesystem>
#include <optional>
#include <sstream>
#include <memory>
#include <array>
namespace fs=std::filesystem;
struct Handle {HANDLE h=INVALID_HANDLE_VALUE;explicit Handle(HANDLE value=INVALID_HANDLE_VALUE):h(value){}~Handle(){if(h!=INVALID_HANDLE_VALUE&&h)CloseHandle(h);}Handle(const Handle&)=delete;Handle& operator=(const Handle&)=delete;void close(){if(h!=INVALID_HANDLE_VALUE&&h)CloseHandle(h);h=INVALID_HANDLE_VALUE;}};
inline void winCheck(bool ok,const char* action){if(!ok)throw std::runtime_error(std::string(action)+" (Windows error "+std::to_string(GetLastError())+")");}
inline Bytes readFile(const fs::path& path){Handle f(CreateFileW(path.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_FLAG_SEQUENTIAL_SCAN,nullptr));winCheck(f.h!=INVALID_HANDLE_VALUE,"Open file");LARGE_INTEGER size{};winCheck(GetFileSizeEx(f.h,&size),"Read size");require(size.QuadPart>=0&&size.QuadPart<=256*1024*1024,"File exceeds size limit");Bytes b(size_t(size.QuadPart));size_t offset=0;while(offset<b.size()){DWORD got{};winCheck(ReadFile(f.h,b.data()+offset,DWORD(std::min(b.size()-offset,size_t(1<<20))),&got,nullptr),"Read file");require(got!=0,"Unexpected end of file");offset+=got;}return b;}
inline void durableWrite(const fs::path& path,const Bytes& bytes,bool exclusive=true){Handle f(CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,exclusive?CREATE_NEW:CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr));winCheck(f.h!=INVALID_HANDLE_VALUE,"Create staged file");size_t at=0;while(at<bytes.size()){DWORD wrote{};winCheck(WriteFile(f.h,bytes.data()+at,DWORD(std::min(bytes.size()-at,size_t(1<<20))),&wrote,nullptr),"Write file");require(wrote!=0,"Short write");at+=wrote;}winCheck(FlushFileBuffers(f.h),"Flush staged file");}
inline Bytes textBytes(const std::string& text){return Bytes(text.begin(),text.end());}
inline std::string hashBytes(const Bytes& b){BCRYPT_ALG_HANDLE alg{};BCRYPT_HASH_HANDLE hash{};require(BCryptOpenAlgorithmProvider(&alg,BCRYPT_SHA256_ALGORITHM,nullptr,0)>=0,"SHA256 provider failed");std::array<unsigned char,32> digest{};bool ok=BCryptCreateHash(alg,&hash,nullptr,0,nullptr,0,0)>=0;if(ok)ok=BCryptHashData(hash,const_cast<PUCHAR>(b.data()),ULONG(b.size()),0)>=0;if(ok)ok=BCryptFinishHash(hash,digest.data(),ULONG(digest.size()),0)>=0;if(hash)BCryptDestroyHash(hash);BCryptCloseAlgorithmProvider(alg,0);require(ok,"SHA256 failed");char output[65]{};for(size_t i=0;i<digest.size();++i)sprintf_s(output+2*i,3,"%02x",unsigned(digest[i]));return output;}
inline void replaceFile(const fs::path& staged,const fs::path& target){if(fs::exists(target))winCheck(ReplaceFileW(target.c_str(),staged.c_str(),nullptr,0,nullptr,nullptr),"Replace target");else winCheck(MoveFileExW(staged.c_str(),target.c_str(),MOVEFILE_WRITE_THROUGH),"Move staged file");}
inline void atomicWrite(const fs::path& target,const Bytes& bytes){fs::path staged=target;staged+=L".native-staged";require(!fs::exists(staged),"A staging file exists; recover the interrupted transaction first");durableWrite(staged,bytes);try{replaceFile(staged,target);}catch(...){fs::remove(staged);throw;}}
inline std::string narrow(const std::wstring& text){if(text.empty())return {};int n=WideCharToMultiByte(CP_UTF8,0,text.data(),int(text.size()),nullptr,0,nullptr,nullptr);std::string s(n,0);WideCharToMultiByte(CP_UTF8,0,text.data(),int(text.size()),s.data(),n,nullptr,nullptr);return s;}
inline std::wstring wide(const std::string& text){if(text.empty())return {};int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,text.data(),int(text.size()),nullptr,0);require(n>0,"Invalid UTF8");std::wstring s(n,0);MultiByteToWideChar(CP_UTF8,0,text.data(),int(text.size()),s.data(),n);return s;}
inline Bytes resource(int id){auto module=GetModuleHandleW(nullptr);auto found=FindResourceW(module,MAKEINTRESOURCEW(id),RT_RCDATA);winCheck(found!=nullptr,"Find embedded payload");auto loaded=LoadResource(module,found);winCheck(loaded!=nullptr,"Load embedded payload");auto data=static_cast<const unsigned char*>(LockResource(loaded));require(data,"Lock embedded payload");return Bytes(data,data+SizeofResource(module,found));}
inline std::vector<std::string> lines(const Bytes& b){std::istringstream in(std::string(b.begin(),b.end()));std::vector<std::string> out;for(std::string s;std::getline(in,s);){if(!s.empty()&&s.back()=='\r')s.pop_back();if(!s.empty())out.push_back(s);}return out;}
