#include "manager.hpp"
#include <commctrl.h>
#include <shobjidl.h>
#include <shellapi.h>
#include <thread>
#include <atomic>
static HWND window,folderBox,listBox,descriptionBox,logBox,applyButton,removeButton,inspectButton,recoverButton;
static HFONT font;static std::atomic<bool> busy=false;static bool changing=false;static uint32_t chosen=allFeatures&~((1u<<12)|(1u<<19));
static constexpr UINT doneMessage=WM_APP+1;
struct Result {std::wstring text;bool failed{};bool inspected{};bool compatible{};uint32_t mask{};};
static std::wstring controlText(HWND w){int n=GetWindowTextLengthW(w);std::wstring s(n+1,0);GetWindowTextW(w,s.data(),n+1);s.resize(n);return s;}
static void updateChecks(){changing=true;for(size_t i=0;i<features.size();++i)ListView_SetCheckState(listBox,int(i),(chosen&(1u<<i))!=0);changing=false;}
static bool needsElevation(const fs::path& folder){auto probe=folder/(L".cd-native-access-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64()));Handle h(CreateFileW(probe.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_TEMPORARY|FILE_FLAG_DELETE_ON_CLOSE,nullptr));if(h.h!=INVALID_HANDLE_VALUE)return false;auto error=GetLastError();if(error==ERROR_ACCESS_DENIED)return true;winCheck(false,"Check installation write access");return false;}
static void elevatedAction(int action,const fs::path& folder,uint32_t mask){wchar_t exe[32768]{};winCheck(GetModuleFileNameW(nullptr,exe,32768)!=0,"Find patch-manager executable");auto report=fs::temp_directory_path()/(L"ChemDrawNative-result-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64())+L".txt");require(folder.wstring().find(L'"')==std::wstring::npos,"Invalid folder path");
 std::wstring args=(action==1?L"--apply":action==2?L"--uninstall":L"--recover");args+=L" \""+folder.wstring()+L"\"";if(action==1)args+=L" "+std::to_wstring(mask);args+=L" --result \""+report.wstring()+L"\"";
 SHELLEXECUTEINFOW info{};info.cbSize=sizeof(info);info.fMask=SEE_MASK_NOCLOSEPROCESS|SEE_MASK_NOASYNC;info.hwnd=window;info.lpVerb=L"runas";info.lpFile=exe;info.lpParameters=args.c_str();info.nShow=SW_HIDE;winCheck(ShellExecuteExW(&info)!=FALSE,"Administrator operation");Handle process(info.hProcess);WaitForSingleObject(process.h,INFINITE);DWORD code{};winCheck(GetExitCodeProcess(process.h,&code),"Read administrator result");std::string message;if(fs::exists(report)){auto bytes=readFile(report);message.assign(bytes.begin(),bytes.end());fs::remove(report);}if(code)throw std::runtime_error(message.empty()?"Administrator operation failed":message);
}
static void setBusy(bool value){busy=value;for(HWND w:{folderBox,listBox,applyButton,removeButton,inspectButton,recoverButton})EnableWindow(w,!value);EnableWindow(GetDlgItem(window,2),!value);}
static void run(int action){if(busy)return;auto folder=controlText(folderBox);auto mask=chosen;setBusy(true);SetWindowTextW(logBox,action==0?L"Discovering function signatures and checking private ABI...":L"Checking files and preparing a reversible transaction...");
 std::thread([folder,mask,action]{auto result=std::make_unique<Result>();try{if(action==0){auto info=inspect(fs::path(folder));result->text=info.text;result->compatible=info.compatible;result->mask=info.mask;result->inspected=true;}
  else {auto root=fs::canonical(fs::path(folder));validateFolder(root);if(needsElevation(root))elevatedAction(action,root,mask);else if(action==3){FolderLock lock(root);noChemDraw(root);recover(root);}else apply(root,mask,action==2);
   result->text=action==3?L"Interrupted transaction rolled back. Inspect the installation before applying patches.":action==2||!mask?L"Original executable restored. Native manager files restored/removed using their baseline. Backup retained.":L"Selected patches installed. Changes take effect when ChemDraw next starts.";}}
  catch(const std::exception& e){result->failed=true;result->text=wide(e.what());}PostMessageW(window,doneMessage,0,reinterpret_cast<LPARAM>(result.release()));}).detach();
}
static HWND make(const wchar_t* cls,const wchar_t* title,DWORD style,int id){HWND w=CreateWindowExW(0,cls,title,WS_CHILD|WS_VISIBLE|style,0,0,10,10,window,HMENU(INT_PTR(id)),GetModuleHandleW(nullptr),nullptr);SendMessageW(w,WM_SETFONT,WPARAM(font),TRUE);return w;}
static void layout(){RECT r;GetClientRect(window,&r);int width=r.right,height=r.bottom;MoveWindow(GetDlgItem(window,20),20,14,width-40,32,TRUE);MoveWindow(GetDlgItem(window,21),20,50,width-40,30,TRUE);MoveWindow(folderBox,20,84,width-140,28,TRUE);MoveWindow(GetDlgItem(window,2),width-110,84,90,28,TRUE);
 int listHeight=std::max(300,(height-235)*58/100);MoveWindow(listBox,20,126,width-40,listHeight,TRUE);ListView_SetColumnWidth(listBox,0,width-92);MoveWindow(descriptionBox,20,132+listHeight,width-40,42,TRUE);
 int y=listHeight+180;MoveWindow(inspectButton,20,y,115,32,TRUE);MoveWindow(applyButton,145,y,155,32,TRUE);MoveWindow(removeButton,310,y,130,32,TRUE);MoveWindow(recoverButton,450,y,120,32,TRUE);MoveWindow(GetDlgItem(window,9),580,y,100,32,TRUE);MoveWindow(GetDlgItem(window,10),690,y,105,32,TRUE);MoveWindow(logBox,20,y+46,width-40,std::max(40,height-y-62),TRUE);}
static void browse(){IFileDialog* dialog=nullptr;if(FAILED(CoCreateInstance(CLSID_FileOpenDialog,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&dialog))))return;DWORD opts{};dialog->GetOptions(&opts);dialog->SetOptions(opts|FOS_PICKFOLDERS|FOS_FORCEFILESYSTEM);dialog->SetTitle(L"Select the folder containing ChemDraw.exe");if(SUCCEEDED(dialog->Show(window))){IShellItem* item=nullptr;if(SUCCEEDED(dialog->GetResult(&item))){PWSTR path=nullptr;if(SUCCEEDED(item->GetDisplayName(SIGDN_FILESYSPATH,&path))){SetWindowTextW(folderBox,path);CoTaskMemFree(path);}item->Release();}}dialog->Release();}
static LRESULT CALLBACK procedure(HWND w,UINT msg,WPARAM a,LPARAM b){switch(msg){case WM_CREATE:{window=w;LOGFONTW lf{};lf.lfHeight=-16;wcscpy_s(lf.lfFaceName,L"Segoe UI");font=CreateFontIndirectW(&lf);
 make(L"STATIC",L"ChemDraw Patch Manager  â€¢  Native C++  |  r107",0,20);make(L"STATIC",L"Save documents and close ChemDraw. Checked features will load on the next launch.",0,21);
 folderBox=make(L"EDIT",L"C:\\Program Files\\RevvitySignalsSoftware\\ChemDrawApplications_x64",WS_BORDER|ES_AUTOHSCROLL,1);make(L"BUTTON",L"Browse...",BS_PUSHBUTTON,2);
 listBox=make(WC_LISTVIEWW,L"",WS_BORDER|LVS_REPORT|LVS_SHOWSELALWAYS|LVS_SINGLESEL,3);ListView_SetExtendedListViewStyle(listBox,LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);LVCOLUMNW col{};col.mask=LVCF_TEXT|LVCF_WIDTH;col.pszText=const_cast<wchar_t*>(L"Patch toggle (shared dependencies enabled automatically)");col.cx=780;ListView_InsertColumn(listBox,0,&col);
 changing=true;for(size_t i=0;i<features.size();++i){LVITEMW item{};item.mask=LVIF_TEXT;item.iItem=int(i);item.pszText=const_cast<wchar_t*>(features[i].name);ListView_InsertItem(listBox,&item);}updateChecks();
 descriptionBox=make(L"STATIC",L"Select a row for its purpose. Canvas state and lifetime hooks form one required foundation.",0,4);inspectButton=make(L"BUTTON",L"Inspect",BS_PUSHBUTTON,5);applyButton=make(L"BUTTON",L"Apply selected",BS_DEFPUSHBUTTON,6);removeButton=make(L"BUTTON",L"Uninstall all",BS_PUSHBUTTON,7);recoverButton=make(L"BUTTON",L"Recover",BS_PUSHBUTTON,8);make(L"BUTTON",L"Select all",BS_PUSHBUTTON,9);make(L"BUTTON",L"Clear all",BS_PUSHBUTTON,10);
 logBox=make(L"EDIT",L"Ready. Inspect discovers offsets and reports compatibility. Applying zero selected patches restores the original executable.\r\nUnknown builds can be inspected; installation requires a verified private ABI profile.",WS_BORDER|ES_MULTILINE|ES_READONLY|ES_AUTOVSCROLL|WS_VSCROLL|WS_HSCROLL,11);layout();return 0;}
 case WM_SIZE:layout();return 0;
 case WM_GETMINMAXINFO:reinterpret_cast<MINMAXINFO*>(b)->ptMinTrackSize={870,780};return 0;
 case WM_COMMAND:if(!busy)switch(LOWORD(a)){case 2:browse();break;case 5:run(0);break;case 6:run(1);break;case 7:run(2);break;case 8:run(3);break;case 9:chosen=allFeatures;updateChecks();break;case 10:chosen=0;updateChecks();break;}return 0;
 case WM_NOTIFY:{auto hdr=reinterpret_cast<NMHDR*>(b);if(hdr->hwndFrom==listBox&&hdr->code==LVN_ITEMCHANGED){auto n=reinterpret_cast<NMLISTVIEW*>(b);if(n->iItem>=0&&n->iItem<int(features.size())){if(n->uNewState&LVIS_SELECTED)SetWindowTextW(descriptionBox,features[n->iItem].detail);if(!changing&&(n->uChanged&LVIF_STATE)&&((n->uOldState^n->uNewState)&LVIS_STATEIMAGEMASK)){bool enabled=ListView_GetCheckState(listBox,n->iItem)!=0;if(enabled)chosen=closeDependencies(chosen|(1u<<n->iItem));else chosen=removeDependents(chosen,n->iItem);updateChecks();}}}return 0;}
 case doneMessage:{std::unique_ptr<Result> result(reinterpret_cast<Result*>(b));setBusy(false);SetWindowTextW(logBox,result->text.c_str());if(result->inspected&&result->mask){chosen=result->mask;updateChecks();}if(result->failed)MessageBoxW(w,result->text.c_str(),L"Patch operation stopped",MB_OK|MB_ICONERROR);return 0;}
 case WM_CLOSE:if(!busy)DestroyWindow(w);return 0;case WM_DESTROY:DeleteObject(font);PostQuitMessage(0);return 0;}
 return DefWindowProcW(w,msg,a,b);}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR,int show){int count{};auto argv=CommandLineToArgvW(GetCommandLineW(),&count);int result=0;fs::path outcome;std::string outcomeText="Operation completed.";
 if(count>=3&&std::wstring(argv[count-2])==L"--result"){outcome=argv[count-1];count-=2;}
 try{
 if(count>1){std::wstring action=argv[1];{require(count>=3,"Usage: --inspect folder report | --apply folder mask | --uninstall folder | --recover folder");fs::path folder=argv[2];if(action==L"--inspect"){require(count==4,"--inspect requires a report path");auto info=inspect(folder);durableWrite(fs::path(argv[3]),textBytes(narrow(info.text)),false);result=info.compatible?0:2;}
 else if(action==L"--apply"){require(count==4,"--apply requires a feature mask");wchar_t* end=nullptr;auto mask=wcstoul(argv[3],&end,0);require(end&&!*end&&mask<=allFeatures,"Invalid mask");apply(folder,uint32_t(mask));}
 else if(action==L"--uninstall")apply(folder,0,true);else if(action==L"--recover"){auto canonical=fs::canonical(folder);FolderLock lock(canonical);noChemDraw(canonical);recover(canonical);}else throw std::runtime_error("Unknown option");}}
 else{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);INITCOMMONCONTROLSEX init{sizeof(init),ICC_LISTVIEW_CLASSES};InitCommonControlsEx(&init);WNDCLASSW cls{};cls.lpfnWndProc=procedure;cls.hInstance=instance;cls.hIcon=LoadIconW(instance,MAKEINTRESOURCEW(201));cls.hCursor=LoadCursorW(nullptr,IDC_ARROW);cls.hbrBackground=HBRUSH(COLOR_WINDOW+1);cls.lpszClassName=L"ChemDrawNativePatcher";RegisterClassW(&cls);window=CreateWindowExW(0,cls.lpszClassName,L"ChemDraw Patch Manager",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,980,930,nullptr,nullptr,instance,nullptr);winCheck(window!=nullptr,"Create window");SendMessageW(window,WM_SETICON,ICON_SMALL,reinterpret_cast<LPARAM>(LoadImageW(instance,MAKEINTRESOURCEW(201),IMAGE_ICON,GetSystemMetrics(SM_CXSMICON),GetSystemMetrics(SM_CYSMICON),LR_SHARED)));ShowWindow(window,show);MSG m{};while(GetMessageW(&m,nullptr,0,0)>0){if(!IsDialogMessageW(window,&m)){TranslateMessage(&m);DispatchMessageW(&m);}}CoUninitialize();}
 }catch(const std::exception& e){result=1;outcomeText=e.what();if(count==1)MessageBoxW(nullptr,wide(e.what()).c_str(),L"ChemDraw Patch Manager",MB_OK|MB_ICONERROR);else {auto path=fs::temp_directory_path()/L"ChemDrawNativePatcher-error.txt";durableWrite(path,textBytes(e.what()),false);}}
 if(!outcome.empty())try{durableWrite(outcome,textBytes(outcomeText),false);}catch(...){result=1;}LocalFree(argv);return result;}
